version: "2.0"
services:
  limesurvey:
    build:
      context: images/limesurvey
      dockerfile: Dockerfile
    volumes:
      - /tmp/upload/:/var/www/html/upload/
    links:
      - lime-db
    depends_on:
      - lime-db
    ports:
      - "8099:80"
    environment:
      - "DB_HOST=applimesurvey_lime-db_1"
      - "DB_PASSWORD=secret"
      - "ADMIN_PASSWORD=vendetta"
  lime-db:
    image: mariadb
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"